### ISSUE TITLE
Deployments explanation

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#117]
https://routify.dev/docs/config/deployments talks about `RewriteRule . __app.html`. I believe this file doesn't exist anymore in the starter and this should be `__index.html`. Is this correct @jakobrosenberg ?

**Comment by jakobrosenberg** [comment]
__index.html is rewritten as __app.html in the dist folder. It's the file served in case of 404s, so technically it could also be Spassr if you wanted to have SSR.

**Comment by Wolfr** [comment]
OK, so it's not a mistake. Independent of any naming discussions, we should explain what is happening at build time some time. On the blog maybe.
