### ISSUE TITLE
afterPageLoad is undocumented

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#122]
The afterPageLoad hook was added in Routify 1.6, but it seems undocumented on the website.

**Comment by Wolfr** [comment]
So this seems to fire, not when the page is loaded, but when you click the same link after the page has been loaded.

Possible starting code for documentation:

```
import { afterPageLoad } from "@sveltech/routify"
$afterPageLoad ((event, store) => {
  console.log("page x");
  return true;
})
```

Input welcome @jakobrosenberg .

**Comment by jakobrosenberg** [comment]
I think this would be the correct approach for an example. ``return true`` is not needed since the hook called after the page change and thus can't guard anything. The store is not present in the parameters (it really shouldn't be in beforeUrlChange either, but breaking changes and all that).

```javascript
import { afterPageLoad } from "@sveltech/routify"
$afterPageLoad ((page) => {
  console.log(page.title);
})
```

**Comment by Wolfr** [comment]
I am trying to make docs for this in https://github.com/sveltech/routify-site-2020/tree/docs/afterpageload - but somehow the tree is reversing in order when I add a new item (url should be first and it last):

![image](https://user-images.githubusercontent.com/12690/82726113-51f87200-9ce2-11ea-9de3-0b38c06d0951.png)

Can you check out what is going on?

**Comment by jakobrosenberg** [comment]
@Wolfr there was an issue with sorting in previous versions, but it should be fixed in the most recent.

**Comment by Wolfr** [comment]
if I switch up to @sveltech/routify": "^1.8.0-beta.7" I have the same problem unfortunately :/

**Comment by jakobrosenberg** [comment]
I'll have a look tonight.

**Comment by Wolfr** [comment]
I think you fixed that bug :) I'll continue work on this branch later.

**Comment by Wolfr** [comment]
Afterpageload is now documented.
