### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#139]
1. Does Routify support code splitting? (I believe so...)
2. How should we document it?

Just posing the questions to start my own thinking.

**Comment by Wolfr** [comment]
I think this is pretty much covered by 1.8 release blog post. Could have further docs, but I think that has to be discussed in a new issue. Closing.

**Comment by premji012** [comment]
Can i name the bunldes? The bundles are generated using an integer value. But i want this to generate bundles with same name everytime. Could i do this?
