### ISSUE TITLE
Single command SCSS: problem when editing partials

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#16]
When you are editing a partial and save it, the SCSS does not get saved.

The new idea that we can work on the site with just 1 command is good, but the workflow doesn't work yet. It only works if you directly edit style.scss, but you work in partials most of the time.

**Comment by Wolfr** [comment]
I investigated this a bit, there are two projects out there that I considered, there is rollup-plugin-scss, which we already use, and there is rollup-plugin-sass. The latter has the benefit that it integrates autoprefixer. Other than that, the projects seem quite similar.

I read the threads at 

* https://github.com/differui/rollup-plugin-sass/issues/29
* https://github.com/thgh/rollup-plugin-scss/issues/3

Both are about the lack of partials support in the plugins. Both seem to point at a solution where Javascript is used to bundle the SCSS i.e. the partial references live in the central JS file, as far as I understand.

This does not really seem like an acceptable solution to me. This will lead to a very dirty main.js file.

**Comment by jakobrosenberg** [comment]
We could possibly spawn the scss watcher rollup.config.js.
