### ISSUE TITLE
Implement content of Helpers page

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#22]
https://routify-2020-khaki.now.sh/helpers

What should be on this page?

**Comment by Wolfr** [comment]
Newest deploy.

https://routify-site-feb.now.sh/helpers/auth

What do you think @jakobrosenberg ?

**Comment by jakobrosenberg** [comment]
I think anything that's in this file

https://github.com/sveltech/routify/blob/master/runtime/helpers.js

**context**
Returns information about the current route

**ready**
If present, will delay SSR rendering until it has been called

**beforeUrlChange**
Hook

**url**
Resolves URLs by path or name

**params**
Returns parameters from the URL

**leftover**
Returns the unconsumed part of the URL

**goto**
Programatically navigate (resolves with the url helper)

**isActive**
Check if a given path is the currently active path.

**getConcestor**
Returns the concestor and sibling ancestors of two routes. (Used for determining transition direction)

**getDirection**
Returns index difference between two paths from an array.



That's the gist of it, but I assume some of them will require clarification.

**Comment by Wolfr** [comment]
I transferred this to Notion so we can improve the clarity of the copy there.

**Comment by Wolfr** [comment]
This is the current URL.

https://routify-2020-au0fp6n5r.now.sh/docs/helpers

I think we should make it more clear how to implement them. I would be lost just looking at this table without having worked on Routify.

**Comment by jakobrosenberg** [comment]
Yes, the helpers page is anything but ready. That might be the only thing holding back the 2020 site at this stage.
