### ISSUE TITLE
Bash syntax highlighting

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#23]
The terminal command help at the bottom of https://routify-2020-khaki.now.sh/configuration/basics needs some bash highlighting.

**Comment by jakobrosenberg** [comment]
Would we gain anything from bash syntax, considering that the documentation isn't bash, but just printed to bash.

**Comment by Wolfr** [comment]
We can just disable syntax highlighting instead for this one? Now it just looks weird with random words highlighted.

![image](https://user-images.githubusercontent.com/12690/75522572-98537300-5a0a-11ea-8e8c-3da3699ebcb6.png)

**Comment by Wolfr** [comment]
![image](https://user-images.githubusercontent.com/12690/77453144-2565ce00-6df7-11ea-8480-e2896b6afeb4.png)

What's up with the user@localhost, can we remove that so the block doesn't become super wide?

**Comment by jakobrosenberg** [comment]
yup. I meant to do that, remind me tomorrow ;)
