### ISSUE TITLE
Unused step in use tailwind css docs

### ISSUE THREAD

**Issue by pybash1** [sveltech/routify-site-2020#239]
For the docs on [how to integrate tailwindcss with routify](https://www.routify.dev/examples/use-tailwind-css), in the second step, last part(Rollup config), I don't think it is needed there. Firstly because the starter template doesn't come with `rollup.config.js` and secondly because I got it working without that step.

**Comment by jakobrosenberg** [comment]
Thanks for the heads up. I don't personally use Tailwind. Maybe @ghostdevv can weigh in on this.

**Comment by ghostdevv** [comment]
The docs are outdated, recently I switched the starter template from rollup to vite - I will update the relevant templates now!

**Comment by ghostdevv** [comment]
The docs have been updated <https://www.routify.dev/examples/use-tailwind-css>

**Comment by pybash1** [comment]
@ghostdevv Thanks!
