### ISSUE TITLE
Examples page

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#24]
https://routify-2020-khaki.now.sh/examples

Examples page needs some content.

- Auth
- Login

Will these be separate pages?

**Comment by Wolfr** [comment]
Just a bit confused, you mentioned a new structure with "Login", on the old site info about "Auth" is under Helpers. So I would like some more guidance on which content will go where.

**Comment by jakobrosenberg** [comment]
We should probably draft a list of concepts to learn. Then separate them into what's covered sufficiently in the API documentation and what needs separate examples. 


- **user**
  - **authentication**
  - **authorization**
  - **login/register**
- **decorators**
  - **transitions**
- **nav-menu**
- **async data**
- **ssr**
- **website simulation**
  - **scroll-lock**
  - **defocus**
- **layouts**
  - **resets**
- **modal** https://example.routify.dev/example/modal/animated/
```

**Comment by Wolfr** [comment]
It might be worthwhile to make a split between what we need to launch the website and what you plan to write in the future. Otherwise the website launch might be delayed due to content plans.
