### ISSUE TITLE
Consider README

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#27]
With the recent changes in Routify, how much of this README is still relevant?

Especially line 8 on code splitting - is this still relevant?

https://github.com/sveltech/routify-site-2020/blob/master/README.md

**Comment by jakobrosenberg** [comment]
It seems it all is, except for this
```
Please make sure that url rewrite is enabled on our server.

For apps without code splitting redirect to index.html
For apps with code splitting redirect to dynamic.html
```
It should be
```
Please make sure that url rewrite is enabled on our server and redirect to __app.html.
```

``__app.html`` is automatically copied from either ``static/__dynamic.html`` or ``static/__bundled.html``.

**Comment by jakobrosenberg** [comment]
Updated it. Should be fine now.
