### ISSUE TITLE
Site launch plan

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#33]
I believe we should just replace https://routify.dev/ (current site) with the routify-site-2020.

Then we just keep working on better docs in the new layout (using Notion)

 Otherwise, we have 2 content trees to compare.

What do you think @jakobrosenberg ?

**Comment by jakobrosenberg** [comment]
Is this a timeline proposal? Sorry, I'm not too sure what you're asking.

**Comment by Wolfr** [comment]
Yes... I am proposing to do it sooner than later :)

**Comment by jakobrosenberg** [comment]
Once the basics are in place, I'm all for it.

**Comment by Wolfr** [comment]
So... are we there yet :D?

**Comment by jakobrosenberg** [comment]
I think We're there. Not at the computer now, but will assign the domain tomorrow. 👍

**Comment by Wolfr** [comment]
Great!
