### ISSUE TITLE
Feedback on decorators page

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#46]
What is the use case for a decorator?

The usage is there, but an example use case would be good.

Then we could add that to this page. 

![image](https://user-images.githubusercontent.com/12690/77529014-306c3d00-6e8f-11ea-8540-bd719bc305c5.png)

**Comment by jakobrosenberg** [comment]
Decorators handle things like transitions. Might be easier to explain on Discord.

**Comment by jakobrosenberg** [comment]
Is this what you had in mind? It will apply a fade transition to every descendant layout and page.

```html
<!-- _FadeDecorator.svelte -->
<script>
  import { fade } from "svelte/transition";
</script>

<div transition:fade>
  <slot />
</div>
```

```html
<!-- _layout.svelte -->
<script>
  import FadeDecorator from "./_FadeDecorator.svelte";
</script>

<slot decorator={FadeDecorator} />
```

**Comment by jakobrosenberg** [comment]
I'm adding the example now.

**Comment by Wolfr** [comment]
Great!

I can imagine people scanning the docs and just wondered what decators are used for, to have an example is great.
