### ISSUE TITLE
The mobile nav somehow lists _fallback

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#55]
<img width="313" alt="Screenshot 2020-03-27 at 14 33 47" src="https://user-images.githubusercontent.com/12690/77761234-01dd9600-7038-11ea-8dd3-e3d911f9abd6.png">

**Comment by Wolfr** [comment]
![image](https://user-images.githubusercontent.com/12690/77761261-0dc95800-7038-11ea-9f77-d8d58a76995a.png)

Some pages also seem to be listed twice.

**Comment by jakobrosenberg** [comment]
damn, let me see what I can do.

**Comment by jakobrosenberg** [comment]
I'm not seeing it. I have a normal mobile menu when I visit routify.dev

**Comment by jakobrosenberg** [comment]
@Wolfr are you sure you're not accidentally looking at localhost or an old cached version?

**Comment by Wolfr** [comment]
Looking live on my device it seems to be fixed so might have been a caching problem. 

Verstuurd vanaf mijn iPhone

**Comment by jakobrosenberg** [comment]
Will close this then.
