### ISSUE TITLE
Add uppercase first to name

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#78]
<img width="441" alt="Screenshot 2020-04-04 at 10 49 31" src="https://user-images.githubusercontent.com/12690/78422745-01f61b00-7662-11ea-9149-c07585f98bed.png">

Not sure where the prettyName is actually called to edit this, so assigning this to you @jakobrosenberg .

**Comment by Wolfr** [comment]
Since I added Next and Previous in #80 this is less necessary, still it would be good to know where prettyName comes from, I don't see any import or function call.

**Comment by jakobrosenberg** [comment]
@Wolfr prettyName is still an internal function, so there's no documentation yet.  In the future it will probably be available as just "name" in a public API object.

For now I've just been using CSS for capitalizing.

**Comment by jakobrosenberg** [comment]
Solved, righit?
