### ISSUE TITLE
Blog content plan

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#85]
* Post 1: Comparison to other routers
  * Question: How does this differ from Sapper?
  * Question: Plans on how to deal with i8n
* Post 2: Guide/screencast - how to use Routify in 10 minutes
* Post 3: Upcoming feature: automatic navigation

Your suggestions welcome.

**Comment by jakobrosenberg** [comment]
I think we should save i18n, till we know a bit more about our url transform vs basepath approach.

**Comment by Wolfr** [comment]
Yes I was just noting the questions from the community... we can say we do not support it at this point in time.

**Comment by Wolfr** [comment]
Here's an iteration of a content plan.

Post 1: Welcome to the Routify blog

* Explain what we plan to do with the blog
* Just the first post

Post 2: Routify on the web

* Talk about where we hang out
* Link to Discord, the Twitter account

Post 3: Comparison to other routers

* Which other routers are out there?
    * https://github.com/EmilTholin/svelte-routing
    * Sapper
* Answer the general question: How does this project differ from competing projects?  
* Talk about friendly competition: we want Svelte to succeed. We love to learn from other projects.
 
Post 4: Guide/screencast - how to use Routify in 10 minutes

* Make a screencast and post this on YouTube, then use this embed in the blog

Post 5: Run through some basic concepts of Routify: layouts, resets. Link to guide/screencast again.

Post 6: Talk about experimental feature: automatic navigation

Post 7: Summarize any discussion about how to deal with i8n; basepath; ? Are there any projects that do this well?

**Comment by jakobrosenberg** [comment]
Just to clarify, we do support i18n through dynamic fallbacks. The reason I prefer to hold off is because dynamic basepaths might be even better.

A structure like this should enable basic i18n support.
```
pages/
  [lang]/
    _layout.svelte
    index.svelte
      blog/
      ...
```

**Comment by Wolfr** [comment]
hmm yes - I think there should also be a suggestion on how to localize strings and a reference implementation - and then this can be documented as basic support. 

Verstuurd vanaf mijn iPhone

**Comment by Wolfr** [comment]
Here's an iteration on the blog content plan;


Post 1: Routify 1.5 - New features

* Welcome people to the blog
* 1.5 features

Post 2: Routify on the web

* Talk about where we hang out
* Link to Discord, the Twitter account
* Also clarify where the different repositories live

Post 3: Comparison to other routers

* Which other routers are out there?
    * [Svelte-Routing](https://github.com/EmilTholin/svelte-routing)
    * [Sapper](https://sapper.svelte.dev/) (not really a router)
* Answer the general question: How does this project differ from other projects?  
* Talk about friendly competition: we want Svelte to succeed. We love to learn from other projects.
 
Post 4: Guide/screencast - how to use Routify in 10 minutes

* Make a screencast and post this on YouTube, then use this embed in the blog

Post 5: Run through some basic concepts of Routify: layouts, resets. Link to guide/screencast again.

Post 6: Talk about how to use automatic navigation features

---

Post X: Summarize any discussion about how to deal with i8n; basepath; ?

**Comment by Wolfr** [comment]
This is a bit dated, we have 3 blog posts that talk about a lot more than what was mentioned here.

**Comment by Wolfr** [comment]
Closing...!
