### ISSUE TITLE
Add: how to implement Google Analytics event tracking

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#88]
In `_layout.svelte`:

```
$: if ($route) {
    ga("set", "page", $route.path);
    ga('send', 'pageview');
  }
```

In index.html:

```
<script>
   window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
   ga('create', 'UA-YOUR-PROPERTY-ID', 'auto');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
```

Note from @jakobrosenberg : page would be a better choice than $route I think. At the moment it's only available in the 1.5 beta.

**Comment by Wolfr** [comment]
Something to document later.

**Comment by jakobrosenberg** [comment]
You might need a check in there to make sure there's no double fire from $route or $page. I don't think there is though. I remember someone asking about it and there was only one trigger per page change, but that was a while ago.

**Comment by Wolfr** [comment]
Shouldn't you just add this to your base index.html file? I don't see a point to put it in the main `_layout`. If it needs to be on every page anyway.

I think this issue is a bit moot then. So will be closing.
