### ISSUE TITLE
Make a choice regarding blog backend

### ISSUE THREAD

**Issue by Wolfr** [sveltech/routify-site-2020#89]
Todo: make a choice on how to implement the blog

options on the table

* Medium
* Blogger
* Wordpress
* Static markdown files, parsed to blog posts

Note that i put a wordpress ready to serve as backend, posts can be accessed through JSON API: http://www.routify.blog/wp-json/wp/v2/posts

I can give the login to show how to create a new post.

**Comment by Wolfr** [comment]
FWIW, for me it doesn't matter that much as long as I can start with something. My preference is just NOT Medium.

**Comment by Wolfr** [comment]
So where did we land now, markdown in blogger?

**Comment by jakobrosenberg** [comment]
Markdown in blogger just for now. It shouldn't be a problem at all to port it later. Also stackedit seems to have blogger and google drive support, so collaboration should be easy.

**Comment by Wolfr** [comment]
In the end we went for static markdown with mdsvex, so I guess we can close this.
